parameters:
    dos.mailer.sender.name: EDITME_IN_PARAM
    dos.mailer.sender.address: EDITME_IN_PARAM
    dos.mailer.notify: EDITME_IN_PARAM

    dos.mailer.renderer_adapter.class: DoS\MailerBundle\Renderer\Adapter\TwigMarkdownAdapter

services:
    dos.mailer.renderer_adapter:
        parent: sylius.email_renderer.adapter.twig
        class: %dos.mailer.renderer_adapter.class%
        calls:
            - [setMarkdownHelper, [@templating.helper.markdown]]
