route_backend_email_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.email:indexAction
        _sylius:
            template: ui:package/backend/Email:index.html.twig
            sortable: true
            sorting:
                code: desc

route_backend_email_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.email:createAction
        _sylius:
            template: ui:package/backend/Email:create.html.twig
            redirect: route_backend_email_index

route_backend_email_update:
    path: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.email:updateAction
        _sylius:
            template: ui:package/backend/Email:update.html.twig
            redirect: route_backend_email_index

route_backend_email_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.email:deleteAction
        _sylius:
            redirect: route_backend_email_index
